// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExchangeGood.Data.Models;

public partial class Notification
{
    public int NotificationId { get; set; }

    public string SenderId { get; set; }

    public string SenderUsername { get; set; }

    public string RecipientId { get; set; }

    public string RecipientUsername { get; set; }

    public string OnwerProductId { get; set; }

    public string ExchangerProductIds { get; set; }

    public string Content { get; set; }

    public DateTime? DateRead { get; set; }

    public DateTime CreatedDate { get; set; }

    public string Type { get; set; }

    public virtual Member Recipient { get; set; }

    public virtual Member Sender { get; set; }
}