// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExchangeGood.Data.Models
{
    public partial class Order
    {
        public Order()
        {
            OrderDetails = new HashSet<OrderDetail>();
        }

        public int OrderId { get; set; }
        public string FeId { get; set; }
        public DateTime CreatedTime { get; set; }
        public DateTime UpdatedTime { get; set; }
        public decimal TotalAmount { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }

        public virtual Member Fe { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}